# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.5.2"
  - "3.5"
  - "3.6"

sudo: required
dist: trusty

notifications:
  email: false

before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb python3-pyqt5 python3-pyqt5.qtmultimedia
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

install:
  - python setup.py install

script:
  - pytest
  - flake8 fibsem_gui

after_success:
  - coveralls
