# Config file for automatic testing at travis-ci.org

language: python
python:
  # - "3.5.2"
  # - "3.5"
  - "3.6"

sudo: required
dist: trusty

notifications:
  email: false

before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb python3-pyqt5 python3-pyqt5.qtmultimedia libqt5multimedia5-plugins
  - sudo ln -s /usr/lib/x86_64-linux-gnu/qt5/plugins/mediaservice/libgstmediaplayer.so /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/plugins/mediaservice/libgstmediaplayer.so
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

install:
  - python setup.py install

script:
  - py.test -s -v --cov=./
  - flake8 fibsem_gui

after_success:
  - coveralls
